name: myenv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.13.9
  - python_abi=3.13
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - a2wsgi==1.10.10
    - absl-py==2.3.1
    - aiosmtplib==5.0.0
    - aiosqlite==0.21.0
    - alembic==1.17.2
    - annotated-types==0.7.0
    - anyio==4.11.0
    - apache-airflow==3.1.3
    - apache-airflow-core==3.1.3
    - apache-airflow-providers-common-compat==1.9.0
    - apache-airflow-providers-common-io==1.6.5
    - apache-airflow-providers-common-sql==1.29.0
    - apache-airflow-providers-smtp==2.3.2
    - apache-airflow-providers-standard==1.9.2
    - apache-airflow-task-sdk==1.1.3
    - argcomplete==3.6.3
    - asgiref==3.11.0
    - astunparse==1.6.3
    - attrs==25.4.0
    - babel==2.17.0
    - cachetools==6.2.2
    - cadwyn==5.4.5
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - colorama==0.4.6
    - colorlog==6.10.1
    - contourpy==1.3.3
    - cron-descriptor==2.0.6
    - croniter==6.0.0
    - cryptography==46.0.3
    - cycler==0.12.1
    - deprecated==1.3.1
    - dill==0.4.0
    - dnspython==2.8.0
    - docstring-parser==0.17.0
    - email-validator==2.3.0
    - et-xmlfile==2.0.0
    - fastapi==0.117.1
    - fastapi-cli==0.0.16
    - flatbuffers==25.9.23
    - fonttools==4.60.1
    - fsspec==2025.10.0
    - gast==0.6.0
    - google-api-core==2.28.1
    - google-api-python-client==2.187.0
    - google-auth==2.41.1
    - google-auth-httplib2==0.2.1
    - google-auth-oauthlib==1.2.3
    - google-cloud-aiplatform==1.71.1
    - google-cloud-bigquery==3.38.0
    - google-cloud-core==2.5.0
    - google-cloud-resource-manager==1.15.0
    - google-cloud-storage==2.19.0
    - google-crc32c==1.7.1
    - google-pasta==0.2.0
    - google-resumable-media==2.8.0
    - googleapis-common-protos==1.72.0
    - greenback==1.2.1
    - greenlet==3.2.4
    - grpc-google-iam-v1==0.14.3
    - grpcio==1.76.0
    - grpcio-status==1.71.2
    - gspread==6.2.1
    - h11==0.16.0
    - h5py==3.15.1
    - httpcore==1.0.9
    - httplib2==0.31.0
    - httptools==0.7.1
    - httpx==0.28.1
    - idna==3.11
    - importlib-metadata==8.7.0
    - iniconfig==2.3.0
    - itsdangerous==2.2.0
    - jinja2==3.1.6
    - joblib==1.5.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - keras==3.12.0
    - kiwisolver==1.4.9
    - lazy-object-proxy==1.12.0
    - libclang==18.1.1
    - libcst==1.8.6
    - linkify-it-py==2.0.3
    - lockfile==0.12.2
    - loguru==0.7.3
    - mako==1.3.10
    - markdown==3.10
    - markdown-it-py==4.0.0
    - markupsafe==3.0.3
    - matplotlib==3.10.7
    - mdurl==0.1.2
    - methodtools==0.4.7
    - ml-dtypes==0.5.4
    - more-itertools==10.8.0
    - msgspec==0.20.0
    - namex==0.1.0
    - narwhals==2.12.0
    - natsort==8.4.0
    - numpy==2.3.5
    - oauthlib==3.3.1
    - openpyxl==3.1.5
    - opentelemetry-api==1.38.0
    - opentelemetry-exporter-otlp==1.38.0
    - opentelemetry-exporter-otlp-proto-common==1.38.0
    - opentelemetry-exporter-otlp-proto-grpc==1.38.0
    - opentelemetry-exporter-otlp-proto-http==1.38.0
    - opentelemetry-proto==1.38.0
    - opentelemetry-sdk==1.38.0
    - opentelemetry-semantic-conventions==0.59b0
    - opt-einsum==3.4.0
    - optree==0.18.0
    - outcome==1.3.0.post0
    - packaging==25.0
    - pandas==2.3.3
    - pathspec==0.12.1
    - pendulum==3.1.0
    - pillow==12.0.0
    - plotly==6.5.0
    - pluggy==1.6.0
    - proto-plus==1.26.1
    - protobuf==5.29.5
    - psutil==7.1.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pycparser==2.23
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pygments==2.19.2
    - pygtrie==2.5.0
    - pyjwt==2.10.1
    - pyparsing==3.2.5
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.17.1
    - pytest==9.0.1
    - python-daemon==3.1.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - python-multipart==0.0.20
    - python-slugify==8.0.4
    - pytz==2025.2
    - pywin32==311
    - pyyaml==6.0.3
    - pyyaml-ft==8.0.0
    - referencing==0.37.0
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - rich==14.2.0
    - rich-argparse==1.7.2
    - rich-toolkit==0.16.0
    - rpds-py==0.29.0
    - rsa==4.9.1
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - screeninfo==0.8.1
    - setproctitle==1.3.7
    - shapely==2.1.2
    - shellingham==1.5.4
    - six==1.17.0
    - sniffio==1.3.1
    - sqlalchemy==2.0.44
    - sqlalchemy-jsonfield==1.0.2
    - sqlalchemy-utils==0.42.0
    - sqlparse==0.5.3
    - starlette==0.48.0
    - structlog==25.5.0
    - svcs==25.1.0
    - tabulate==0.9.0
    - tenacity==9.1.2
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.20.0
    - termcolor==3.2.0
    - text-unidecode==1.3
    - threadpoolctl==3.6.0
    - typer==0.20.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - uc-micro-py==1.0.3
    - universal-pathlib==0.2.6
    - uritemplate==4.2.0
    - urllib3==2.5.0
    - uuid6==2025.0.1
    - uvicorn==0.38.0
    - vertexai==1.71.1
    - watchfiles==1.1.1
    - websockets==15.0.1
    - werkzeug==3.1.3
    - win32-setctime==1.2.0
    - wirerope==1.0.0
    - wrapt==2.0.1
    - zipp==3.23.0
prefix: C:\Users\eyalb\anaconda3\envs\myenv
